source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks! :linkage => :static

workspace '../RoxieMobile.ContentProviders/ContentProviders.xcworkspace'


# MARK: - Sources

target 'ContentProviders.SQLite' do
  project '../RoxieMobile.ContentProviders/Sources/SQLite/ContentProviders.SQLite.xcodeproj'

  # Dependencies
  pod 'CryptoSwift', '~> 1.4.3'
  pod 'GRDB.swift/SQLCipher', '~> 5.21.0'
  pod 'SwiftCommons/Concurrent', '~> 1.6.3'
  pod 'SwiftCommons/Extensions', '~> 1.6.3'
  pod 'ZIPFoundation', '~> 0.9.13'
end
